### ISSUE TITLE
incompatible with nerfstudio 0.3.4 and wont run on 0.2.2

### ISSUE THREAD

**Issue by MbertoldiNormal** [nerfstudio-project/nerfstudio-method-template#2]
im running 0.3.4 and when im trying to ton install with pip i have this error message

**ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
nerfstudio-method-template 0.1.0 requires nerfstudio>=0.3.0, but you have nerfstudio 0.2.2 which is incompatible.
  torchaudio 2.1.0+cu118 requires torch==2.1.0+cu118, but you have torch 1.13.1 which is incompatible.
Successfully installed google-auth-oauthlib-0.4.6 nerfstudio-0.2.2 tensorboard-2.9.0 tensorboard-data-server-0.6.1 torch-1.13.1 torchvision-0.14.1 zipnerf-0.1.0**

so i tried to uninstall both nerfstudio and torch 1.31.1 and try to run pip install -e. again to see if it'll take the right package but no 

**ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
nerfstudio-method-template 0.1.0 requires nerfstudio>=0.3.0, but you have nerfstudio 0.2.2 which is incompatible.
torchaudio 2.1.0+cu118 requires torch==2.1.0+cu118, but you have torch 1.13.1 which is incompatible.
Successfully installed nerfstudio-0.2.2 torch-1.13.1 zipnerf-0.1.0**

**zipnerf 0.1.0 requires nerfstudio==0.2.2, but you have nerfstudio 0.3.0 which is incompatible.**

please help me out i think im in a big loop

**Comment by MbertoldiNormal** [comment]
** update **

when i finally have no more error message when install -e. and trying to run `ns-train zipnerf` i get this error message

(nerfstudio) C:\Users\Pigiste1\nerfstudio\zipnerf-nerfstudio-main>ns-train zipnerf-nerfstudio-main C:\Users\Pigiste1\nerfstudio\data\shutterstock_1080988859.mov
Traceback (most recent call last):
  File "C:\Users\Pigiste1\miniconda\envs\nerfstudio\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\Pigiste1\miniconda\envs\nerfstudio\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\Pigiste1\miniconda\envs\nerfstudio\Scripts\ns-train.exe\__main__.py", line 4, in <module>
  File "C:\Users\Pigiste1\miniconda\envs\nerfstudio\lib\site-packages\scripts\train.py", line 49, in <module>
    from nerfstudio.configs.method_configs import AnnotatedBaseConfigUnion
  File "C:\Users\Pigiste1\miniconda\envs\nerfstudio\lib\site-packages\nerfstudio\configs\method_configs.py", line 50, in <module>
    from nerfstudio.field_components.temporal_distortions import TemporalDistortionKind
  File "C:\Users\Pigiste1\miniconda\envs\nerfstudio\lib\site-packages\nerfstudio\field_components\__init__.py", line 17, in <module>
    from .encodings import Encoding, ScalingAndOffset
  File "C:\Users\Pigiste1\miniconda\envs\nerfstudio\lib\site-packages\nerfstudio\field_components\encodings.py", line 35, in <module>
    import tinycudann as tcnn
  File "C:\Users\Pigiste1\miniconda\envs\nerfstudio\lib\site-packages\tinycudann\__init__.py", line 9, in <module>
    from tinycudann.modules import free_temporary_memory, NetworkWithInputEncoding, Network, Encoding
  File "C:\Users\Pigiste1\miniconda\envs\nerfstudio\lib\site-packages\tinycudann\modules.py", line 19, in <module>
    raise EnvironmentError("Unknown compute capability. Ensure PyTorch with CUDA support is installed.")
OSError: Unknown compute capability. Ensure PyTorch with CUDA support is installed.

**Comment by tancik** [comment]
Going to close because this repo is for the nerfstudio-template, not the nerfstudio repo. Also questions like this are best answered in the [discord](https://discord.gg/RyVk6w5WWP). It looks like the pytorch installed in incorrect, it needs to be a CUDA version. Make sure you have a nvidia GPU, and search online for pytorch install guides with CUDA support.
